/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function WaterSplash(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/chandle.gltf");
  return (
    <group ref={group} {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass.geometry}
        material={materials.glass}
        position={[0, 2.28, 0]}
      />
      <group position={[0, 2.29, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Plane003.geometry}
          material={materials["Metal_lampochka.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Plane003_1.geometry}
          material={materials["glass_architectural.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Plane003_2.geometry}
          material={materials["glass.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_Plane003_3.geometry}
          material={materials["emission spiral.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Metal.geometry}
        material={materials["Metal Lustra"]}
        position={[0, 2.58, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grystal_Glass.geometry}
        material={materials.Crystal}
        position={[0, 2.22, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Provod.geometry}
        material={materials["provod.000"]}
        position={[-0.03, 2.64, 0]}
      />
    </group >
  );
}

useGLTF.preload("/chandle.gltf");

